import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { ShopProvider } from "./ShopProvider";
import { getShopSession } from "@/app/actions/shop";
import HeaderNav from "./HeaderNav";
import SiteFooter from "./SiteFooter";
import HeaderSearch from "./HeaderSearch";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getShopSession();


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-white">
        <ShopProvider initialBasket={session.basket} initialFavs={session.favs}>
          <div className="flex min-h-screen w-full flex-col">
            <header className="w-full">
              <div className="mx-auto flex w-full max-w-[1680px] items-center gap-6 px-4 py-8">
                <Link href="/" className="font-bold">
                  MiniStore
                </Link>

                <HeaderSearch />

                <HeaderNav />
              </div>
            </header>

            <main className="w-full flex-1">{children}</main>

            <SiteFooter />
          </div>
        </ShopProvider>
      </body>
    </html>
  );
}
