import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { ShopProvider } from "./ShopProvider";
import { getShopSession } from "@/app/actions/shop";
import HeaderNav from "./HeaderNav";
import SiteFooter from "./SiteFooter";
import HeaderSearch from "./HeaderSearch";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    title: "Mini Store",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getShopSession();


  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-white">
        <ShopProvider initialSession={session}>
          <div className="flex min-h-screen w-full flex-col">
            <header className="w-full border-b border-neutral-200 bg-white">
              <div className="mx-auto grid w-full max-w-[1680px] grid-cols-[minmax(0,1fr)_auto] items-center gap-x-3 gap-y-4 px-4 py-5 sm:gap-x-8 xl:grid-cols-[auto_minmax(16rem,48rem)_minmax(0,1fr)] xl:py-6">
                <Link
                  href="/"
                  aria-label="MiniStore home"
                  className="inline-flex shrink-0 -translate-y-[3px] flex-col self-center text-black no-underline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-black"
                >
                  <span
                    aria-hidden="true"
                    className="pl-[0.12em] text-[0.72rem] font-black leading-none tracking-[0.32em]"
                  >
                    MINI
                  </span>
                  <span
                    aria-hidden="true"
                    className="-mt-[0.05em] text-[2.35rem] font-light leading-[0.82] tracking-[0.01em]"
                  >
                    STORE
                  </span>
                </Link>

                <HeaderSearch />

                <HeaderNav />
              </div>
            </header>

            <main className="w-full flex-1">{children}</main>

            <SiteFooter />
          </div>
        </ShopProvider>
      </body>
    </html>
  );
}
